version: '3'

services:
    php:
        build: ./docker/php
        ports:
            - "8000:80"
        volumes:
            - ./www:/var/www/html
            - ./private/secrets:/var/www/private/secrets
        depends_on:
          - database
        links:
            - database
    database:
        image: mysql:5.6
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql
        env_file:
          - ./private/secrets/db_env
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        env_file:
          - ./private/secrets/db_env
        depends_on:
          - database
        links:
            - database:db
